(()=>{
 document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/slideshow.css">');
 const page=location.pathname.split('/').pop()||'index.html',mark='<span class="logo-image"><img src="assets/images/axiom-logo-dark.png" alt="Axiom Church logo"></span>';
 // Grouped nav. TODO: #rally-point, #baptism and #serve get Planning Center URLs; #rooted destination is undecided.
 const NAV=[['group','I\'m New','nav-new',[['visit.html','Plan a visit'],['kids.html','Kids']]],['group','About','nav-about',[['about.html','Who we are'],['beliefs.html','What we believe']]],['link','Messages','messages.html'],['group','Next Steps','nav-next',[['next-steps.html','What is my Next Step?'],['baptism.html','Get Baptized'],['teams.html','Join a Team'],['prayer.html','Need Prayer?'],['https://axiomcares.netlify.app','Need Help?','ext']]],['link','Give','give.html']];
 const item=([h,l,x])=>`<a href="${h}"${x==='ext'?' target="_blank" rel="noopener"':''}${page===h?' class="active" aria-current="page"':''}>${l}</a>`;
 const menu=NAV.map(n=>n[0]==='link'?`<a class="link${page===n[2]?' active':''}" href="${n[2]}"${page===n[2]?' aria-current="page"':''}>${n[1]}</a>`:`<div class="group"><button class="trigger${n[3].some(i=>i[0]===page)?' active':''}" type="button" aria-expanded="false" aria-controls="${n[2]}">${n[1]}<span class="chev" aria-hidden="true"></span></button><div class="panel" id="${n[2]}">${n[3].map(item).join('')}</div></div>`).join('');
 document.querySelector('[data-header]').innerHTML=`<header class="header"><nav class="nav wrap" aria-label="Primary"><a class="logo" href="index.html">${mark}<b>Axiom Church</b></a><div class="menu" id="menu">${menu}<a class="pill fill menu-cta" href="visit.html">Plan a Visit</a></div><a class="pill fill" href="visit.html">Plan a Visit</a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="menu">☰</button></nav></header>`;
 document.querySelector('[data-footer]').innerHTML=`<footer class="footer"><div class="wrap"><div class="footer-main"><div><h3>A place you can<br>stop pretending.</h3><p>A brand new church for people who thought they would never step foot in one.</p></div><div><h4>I&rsquo;m New</h4><ul><li><a href="visit.html">Plan a visit</a></li><li><a href="kids.html">Kids</a></li><li><a href="messages.html">Messages</a></li></ul></div><div><h4>About</h4><ul><li><a href="about.html">Who we are</a></li><li><a href="beliefs.html">What we believe</a></li><li><a href="give.html">Give</a></li></ul></div><div><h4>Next Steps</h4><ul><li><a href="next-steps.html">What is my Next Step?</a></li><li><a href="baptism.html">Get Baptized</a></li><li><a href="teams.html">Join a Team</a></li><li><a href="prayer.html">Need Prayer?</a></li><li><a href="https://axiomcares.netlify.app" target="_blank" rel="noopener">Need Help?</a></li></ul></div><div><h4>Sunday</h4><p>10:00 AM<br>Camacho Elementary<br>501 Municipal Dr<br>Leander, TX 78641</p><a href="tel:5122655718">512-265-5718</a></div></div><div class="footer-bottom"><span>© 2026 Axiom Church</span><span>Leander, Texas</span></div></div></footer>`;
 const slides=[...document.querySelectorAll('.hero-slideshow img')];if(slides.length>1&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let current=0;setInterval(()=>{slides[current].classList.remove('active');current=(current+1)%slides.length;slides[current].classList.add('active')},5500)}
 const h=document.querySelector('.header');addEventListener('scroll',()=>{if(scrollY>80)h.classList.add('compact');else if(scrollY<24)h.classList.remove('compact')},{passive:true});const t=document.querySelector('.menu-toggle'),m=document.querySelector('.menu'),groups=[...document.querySelectorAll('.menu .group')],narrow=matchMedia('(max-width: 900px)');const setOpen=(g,o)=>{g.classList.toggle('open',o);g.querySelector('.trigger').setAttribute('aria-expanded',o)};const closeAll=()=>groups.forEach(g=>setOpen(g,false));groups.forEach(g=>g.querySelector('.trigger').addEventListener('click',()=>{const o=!g.classList.contains('open');if(!narrow.matches)closeAll();setOpen(g,o)}));const setDrawer=o=>{m.classList.toggle('open',o);t.setAttribute('aria-expanded',o);t.textContent=o?'×':'☰';if(!o)closeAll()};t.addEventListener('click',()=>setDrawer(!m.classList.contains('open')));document.addEventListener('click',e=>{if(!e.target.closest('.menu .group'))closeAll()});document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const g=document.activeElement&&document.activeElement.closest('.menu .group');if(g&&g.classList.contains('open'))g.querySelector('.trigger').focus();closeAll();if(narrow.matches&&m.classList.contains('open')){setDrawer(false);t.focus()}});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('[data-reveal]').forEach(x=>io.observe(x));document.querySelectorAll('.faq button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));const f=document.querySelector('form');if(f)f.onsubmit=e=>{e.preventDefault();document.querySelector('[data-status]').textContent='Thanks! This local preview is ready to be connected to your form provider.';f.reset()};
if(document.querySelector('.fold-btn')){document.querySelectorAll('.fold-btn').forEach(b=>{b.addEventListener('click',()=>{const f=b.closest('.fold'),open=!f.classList.contains('open');f.classList.toggle('open',open);b.setAttribute('aria-expanded',open)})})}
/* kids page: quote reel. Duplicate the set once, drift left, loop; pause on touch, hover or focus. */
const reel=document.getElementById('reel'),track=document.getElementById('reelTrack');
if(reel&&track&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const n=track.children.length;for(let i=0;i<n;i++){const c=track.children[i].cloneNode(true);c.setAttribute('aria-hidden','true');track.appendChild(c)}let hold=false,resume=0,pos=0,last=0;const stop=()=>{hold=true;clearTimeout(resume)},go=()=>{clearTimeout(resume);resume=setTimeout(()=>{hold=false;pos=reel.scrollLeft},1800)};['pointerdown','touchstart','mouseenter','focusin','wheel'].forEach(e=>reel.addEventListener(e,stop,{passive:true}));['pointerup','touchend','mouseleave','focusout','wheel'].forEach(e=>reel.addEventListener(e,go,{passive:true}));requestAnimationFrame(function tick(t){const dt=last?Math.min(t-last,60):0;last=t;const loop=track.children[n].offsetLeft-track.children[0].offsetLeft;if(!hold){pos+=dt*0.035;if(pos>=loop)pos-=loop;reel.scrollLeft=pos}else if(reel.scrollLeft>=loop){reel.scrollLeft-=loop}requestAnimationFrame(tick)})}
})();
